ReportDefinitions:
- reportName: PTReceiptRegister
  decryptionPathId: PTReceiptRegister
  summary: Report is used for audit, day-end, and year-end finance reconciliation activities 
  version: 1.0.0
  moduleName: pt-reports
  sourceColumns:
  - name: receiptnumber
    label: reports.pt.receiptnumber
    type: string
    source: pt
    total: false
  - name: paymentdate
    label: reports.pt.paymentdate
    type: string
    source: pt
    total: false
  - name: name
    label: reports.pt.consumername
    type: string
    source: pt
    total: false 
  - name: amountCollected
    label: reports.pt.amountCollected
    type: string
    source: pt
    total: false
  - name: payerName
    label: reports.pt.payerName
    type: string
    source: pt
    total: false
  - name: transactionnumber
    label: reports.pt.transactionnumber
    type: string
    source: pt
    total: false
  - name: chequeNo
    label: reports.pt.chequeNo
    type: string
    source: pt
    total: false

searchParams:
  - name: fromDate
    label: reports.pt.fromDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate >= $fromDate
  - name: toDate
    label: reports.pt.toDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate <= $toDate
  - name: receiptstatus
    label: receiptstatus
    type: singlevaluelist
    pattern: 'list://NEW:New,DEPOSITED:Deposited,DISHONOURED:Dishonoured'
    source: pt
    isMandatory: false
    searchClause: AND ep.paymentstatus = $receiptstatus
  - name: collectorname
    label: reports.pt.collectorname
    type: singlevaluelist
    pattern: http://egov-hrms:8080/egov-hrms/employees/_search?tenantId=$tenantid&roles=PT_CEMP|$.Employees[*].user.id|$.Employees[*].user.name
    source: pt
    wrapper: true
    isMandatory: false
    searchClause: AND ep.createdby= $collectorname   
  query: |
        SELECT receiptnumber,payerName,To_char(To_timestamp(ed.receiptdate / 1000), 'DD/MM/YYYY') AS paymentdate,user.name as name
        transactionnumber,totalamountpaid AS amountCollected,payment.instrumentnumber as chequeNo FROM egcl_payment AS ep
        JOIN egcl_paymentdetail AS ed ON ep.id = ed.paymentid JOIN egcl_bill as bill on ed.billid=bill.id JOIN eg_pt_property as property bill.consumercode=property.propertyid JOIN eg_pt_owner as owner on property.id=owner.propertyid  JOIN eg_user as user on owner.ownerinfouuid=user.uuid where 1=1  and ed.businessservice='PT' and ep.paymentstatus !='CANCELLED'
  orderby: order by ed.receiptdate desc

- reportName: PTCollectionReport
  decryptionPathId: PTCollectionReport
  summary: It helps administrators track the collection in the ULB and the employee collection performance. 
  version: 1.0.0
  moduleName: pt-reports
  sourceColumns:
  - name: receiptnumber
    label: reports.pt.receiptnumber
    type: string
    source: pt
    total: false
  - name: locality
    label: reports.pt.locality
    type: string
    source: pt
    total: false
    localisationPrefix: TENANTS_MOHALLA_
    isLocalisationRequired: true
  - name: name
    label: reports.pt.collectorname
    type: string
    source: pt
    total: false
  - name: paymentinstrument
    label: reports.pt.paymentinstrument
    type: string
    source: pt
    total: false
  - name: transactionnumber
    label: reports.pt.transactionnumber
    type: string
    source: pt
    total: false
  - name: amountCollected
    label: reports.pt.amountCollected
    type: string
    source: pt
    total: true
  - name: paymentdate
    label: reports.pt.paymentdate
    type: string
    source: pt
    total: false
  searchParams:
  - name: fromDate
    label: reports.pt.fromDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate >= $fromDate
  - name: toDate
    label: reports.pt.toDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate <= $toDate
  - name: locality
    label: reports.mcollect.locality
    type: singlevaluelist
    pattern: http://egov-location.egov:8080/egov-location/location/v11/boundarys/_search?hierarchyTypeCode=ADMIN&boundaryType=Locality&tenantId=$tenantid|$.TenantBoundary[0].boundary.*.code|$.TenantBoundary[0].boundary.*.code
    source: pt
    wrapper: true
    isMandatory: false
    localisationPrefix: TENANTS_MOHALLA_
    isLocalisationRequired: true
    searchClause: AND ptd.locality = $locality  
  - name: paymentinstrument
    label: paymentinstrument
    type: singlevaluelist
    pattern: 'list://CASH:CASH,ONLINE:ONLINE,CARD:CARD,DD:DD,CHEQUE:CHEQUE'
    source: pt
    isMandatory: false
    searchClause: AND paymentmode = $paymentinstrument  
  query: |
        SELECT receiptnumber,ptd.locality AS locality, users.name as name,To_char(To_timestamp(ed.receiptdate / 1000), 'DD/MM/YYYY') AS paymentdate,
        transactionnumber,totalamountpaid AS amountCollected,paymentmode AS paymentinstrument FROM egcl_payment AS ep
        JOIN egcl_paymentdetail AS ed ON ep.id = ed.paymentid JOIN egcl_bill  as bill on ed.billid=bill.id JOIN eg_pt_property as property on bill.consumercode=property.propertyid JOIN eg_pt_address as ptd on property.id=ptd.propertyid JOIN eg_user as users on ep.createdby::int=users.id  where 1=1  and ed.businessservice='PT' and ep.paymentstatus !='CANCELLED'
  orderby: order by ed.receiptdate desc
  
- reportName: DefaulterReport
  summary: Report is usually generated weekly/monthly to send notice to the defaulters and used only in the demand-based systems.
  version: 1.0.0
  moduleName: pt-reports
  sourceColumns:
  - name: propertyid
    label: reports.pt.propertyid
    type: string
    source: pt
    total: false
  - name: collectorname
    label: reports.pt.collectorname
    type: string
    source: pt
    total: false
  - name: locality
    label: reports.pt.locality
    type: string
    source: pt
    total: false
  - name: propertystatus
    label: reports.pt.propertystatus
    type: string
    source: pt
    total: false
  - name: amountCollected
    label: reports.pt.amountCollected
    type: string
    source: pt
    total: false
  - name: usagetype
    label: reports.pt.usagetype
    type: string
    source: pt
    total: false
  - name: collectorname
    label: reports.pt.collectorname
    type: string
    source: pt
    total: false
  searchParams:
  - name: locality
    label: reports.pt.locality
    type: singlevaluelist
    pattern: 'list://Amritsar:Amritsar,Punjab:Punjab,Maharastra:Maharastra'
    source: pt
    isMandatory: false
    searchClause: AND ea.locality >= $locality
  - name: usagetype
    label: reports.pt.usagetype
    type: singlevaluelist
    pattern: 'list://Residential:Residential,Non-Residential:Non-Residential,Mixed:Mixed'
    source: pt
    isMandatory: false
    searchClause: AND ep.usagecategory <= $usagetype 
  query: |
        SELECT ea.propertyid,ep.usagecategory AS usagetype,ep.status AS propertystatus,ea.locality,epp.payername AS collectorname,epp.totalamountpaid AS amountcollected 
        FROM eg_pt_property ep join eg_pt_address ea ON ea.propertyid = ep.propertyid JOIN egcl_payment epp on ep.tenantid=epp.tenantid where 1=1
